// funfacts.js - a curated, local set of fun maths/number facts (v1.2).
// LOCAL-FIRST by design: no network, no API, no tracking. All facts are bundled here so
// Fun Facts works fully offline, matching MathFun's data/privacy stance. Kid-friendly.
// Each fact is { emoji, text }.

const FACTS = [
  { emoji: '\u2795', text: 'Adding two odd numbers always gives an even number. Try it: 3 + 5 = 8!' },
  { emoji: '\u2796', text: 'Subtracting a number from itself always gives zero. 7 \u2212 7 = 0, every time.' },
  { emoji: '\u2716\uFE0F', text: 'Any number times zero is zero. Even a million times zero is just 0!' },
  { emoji: '\u2716\uFE0F', text: 'Any number times one stays the same. 9 \u00D7 1 = 9.' },
  { emoji: '\u2797', text: 'Dividing a number by one leaves it unchanged. 42 \u00F7 1 = 42.' },
  { emoji: '\uD83D\uDD22', text: 'Zero is the only number that is neither positive nor negative.' },
  { emoji: '\uD83E\uDDE0', text: 'The word "hundred" comes from an old word "hundrath", which actually meant 120 long ago!' },
  { emoji: '\u267E\uFE0F', text: 'There is no biggest number. You can always add one more, forever!' },
  { emoji: '\uD83D\uDD1F', text: 'We count in tens because we have ten fingers. That is why it is called the decimal system.' },
  { emoji: '\uD83C\uDF1F', text: 'Multiplying by 10 just adds a zero: 6 \u00D7 10 = 60. Handy trick!' },
  { emoji: '\uD83D\uDD01', text: 'In multiplication, order does not matter: 4 \u00D7 7 is the same as 7 \u00D7 4.' },
  { emoji: '\uD83C\uDFB2', text: 'A "prime" number can only be divided by 1 and itself. 2, 3, 5 and 7 are primes.' },
  { emoji: '2\uFE0F\u20E3', text: 'Two is the only even prime number. Every other even number can be halved.' },
  { emoji: '\uD83E\uDD1D', text: 'Numbers that read the same forwards and backwards, like 121 or 3443, are called palindromes.' },
  { emoji: '\uD83C\uDF70', text: 'To share fairly, you divide. 12 cakes shared by 3 friends is 12 \u00F7 3 = 4 each!' },
  { emoji: '\u26A1', text: 'A quick doubling trick: 2 \u00D7 8 is just 8 + 8 = 16.' },
  { emoji: '\uD83D\uDD1F', text: 'The digits of any number in the 9 times table add up to 9: 9 \u00D7 4 = 36, and 3 + 6 = 9!' },
  { emoji: '\uD83E\uDDEE', text: 'The equals sign (=) was invented in 1557 because writing "is equal to" over and over was tiring.' },
  { emoji: '\uD83C\uDFAF', text: 'A dozen means 12. Half a dozen is 6. Eggs often come in a dozen!' },
  { emoji: '\uD83D\uDE80', text: 'Counting by fives is easy: 5, 10, 15, 20... it is just the 5 times table.' },
  { emoji: '\uD83E\uDD1F', text: 'Adding two even numbers always gives an even number: 4 + 6 = 10.' },
  { emoji: '\uD83D\uDD04', text: 'Adding numbers in any order gives the same answer: 2 + 9 = 9 + 2.' },
  { emoji: '\uD83E\uDDF1', text: 'A square number is a number times itself: 3 \u00D7 3 = 9, so 9 is a square number.' },
  { emoji: '\uD83D\uDCC8', text: 'The square numbers go 1, 4, 9, 16, 25... the gaps between them are the odd numbers!' },
  { emoji: '\uD83D\uDC49', text: 'To multiply by 5, multiply by 10 and then halve it: 5 \u00D7 8 = half of 80 = 40.' },
  { emoji: '\u270B', text: 'The 9 times table on your fingers: fold the finger for the number and count the rest.' },
  { emoji: '\uD83D\uDD22', text: 'An even number always ends in 0, 2, 4, 6 or 8.' },
  { emoji: '\uD83D\uDD22', text: 'An odd number always ends in 1, 3, 5, 7 or 9.' },
  { emoji: '\uD83C\uDF82', text: 'Sharing 0 sweets between friends gives everyone 0. Zero divided by anything is 0.' },
  { emoji: '\u26D4', text: 'You can never divide by zero. It simply has no answer!' },
  { emoji: '\uD83D\uDD01', text: 'Division undoes multiplication: 6 \u00D7 4 = 24, and 24 \u00F7 4 = 6.' },
  { emoji: '\u2795', text: 'Subtraction undoes addition: 8 + 3 = 11, and 11 \u2212 3 = 8.' },
  { emoji: '\uD83E\uDDEE', text: 'Adding 0 to a number changes nothing: 47 + 0 = 47.' },
  { emoji: '\uD83D\uDCCF', text: 'A triangle has 3 sides, a square has 4, a pentagon 5 and a hexagon 6.' },
  { emoji: '\u2B50', text: 'A star shape often has 5 points, one for each of its 5 corners.' },
  { emoji: '\uD83D\uDD52', text: 'A clock face uses 12 numbers, and there are 60 minutes in an hour.' },
  { emoji: '\uD83D\uDCC5', text: 'There are 7 days in a week and about 30 days in a month.' },
  { emoji: '\uD83D\uDCC6', text: 'A year has 365 days, but a leap year has 366 - with an extra day in February!' },
  { emoji: '\uD83D\uDD5B', text: 'There are 24 hours in a day and 1,440 minutes in a whole day.' },
  { emoji: '\uD83D\uDCB0', text: '100 pennies make 1 pound, so 50 pennies is half a pound.' },
  { emoji: '\uD83D\uDD1F', text: 'Ten tens make a hundred, and ten hundreds make a thousand.' },
  { emoji: '\uD83D\uDCA1', text: 'To multiply by 100, add two zeros: 7 \u00D7 100 = 700.' },
  { emoji: '\u2702\uFE0F', text: 'Halving is dividing by 2. Half of 18 is 9.' },
  { emoji: '\uD83C\uDF55', text: 'A quarter means one of four equal parts. A pizza cut into 4 gives quarters.' },
  { emoji: '\uD83E\uDDC1', text: 'One half is bigger than one quarter, even though 4 is bigger than 2. Funny, right?' },
  { emoji: '\uD83D\uDD03', text: 'Doubling then halving brings you back to the start: 6 doubled is 12, halved is 6.' },
  { emoji: '\uD83C\uDFAF', text: 'The number 1 is not a prime number - primes need exactly two different factors.' },
  { emoji: '\uD83D\uDD0D', text: 'Factors are numbers that divide exactly: the factors of 12 are 1, 2, 3, 4, 6 and 12.' },
  { emoji: '\uD83D\uDCE6', text: 'A multiple is what you get in a times table: 15 is a multiple of 5 and of 3.' },
  { emoji: '\uD83E\uDD16', text: 'Computers count using just two digits, 0 and 1. That is called binary.' },
  { emoji: '\uD83D\uDCCA', text: 'The 2 times table is all the even numbers: 2, 4, 6, 8, 10...' },
  { emoji: '\uD83E\uDDEE', text: 'A "sum" is really an addition, but people often say it for any maths question.' },
  { emoji: '\uD83D\uDD3A', text: 'The biggest single digit is 9. After that you need two digits for 10.' },
  { emoji: '\uD83D\uDD22', text: 'The number 40 (forty) is the only number whose letters are in alphabetical order in English.' },
  { emoji: '\uD83C\uDFB2', text: 'Opposite sides of a dice always add up to 7: 1 and 6, 2 and 5, 3 and 4.' },
  { emoji: '\uD83D\uDC63', text: 'Counting your steps is maths in action - every step adds one more.' },
  { emoji: '\uD83C\uDF08', text: 'A rainbow is often said to have 7 colours.' },
  { emoji: '\uD83E\uDDA4', text: 'An octopus has 8 arms - "oct" means eight, like in octagon (8 sides).' },
  { emoji: '\uD83D\uDD77\uFE0F', text: 'A spider has 8 legs - that is why it is not an insect (insects have 6).' },
  { emoji: '\uD83D\uDC1D', text: 'Bees build honeycomb from hexagons - shapes with 6 sides that fit together perfectly.' },
  { emoji: '\u26BD', text: 'A football is often stitched from 12 pentagons and 20 hexagons.' },
  { emoji: '\uD83C\uDFC0', text: 'A basketball team has 5 players on court, so two teams make 10.' },
  { emoji: '\uD83E\uDD1A', text: 'You have 10 fingers and 10 toes - 20 altogether!' },
  { emoji: '\uD83D\uDCCF', text: 'A full turn around a circle is 360 degrees. Half a turn is 180.' },
  { emoji: '\uD83D\uDCD0', text: 'A right angle is exactly 90 degrees, like the corner of a book.' },
  { emoji: '\uD83D\uDD3C', text: 'Three angles inside any triangle always add up to 180 degrees.' },
  { emoji: '\uD83D\uDD22', text: 'The number after 999 is 1,000. Adding one can grow the number of digits!' },
  { emoji: '\uD83E\uDD73', text: 'A million is 1,000 thousands - that is a lot of zeros: 1,000,000.' },
  { emoji: '\uD83D\uDE80', text: 'A billion is a thousand millions. Written out it has nine zeros!' },
  { emoji: '\u23F3', text: 'Counting to a million out loud would take you about 3 weeks without stopping.' },
  { emoji: '\uD83E\uDDE9', text: 'Odd number minus odd number is always even: 9 \u2212 3 = 6.' },
  { emoji: '\uD83E\uDDE9', text: 'Even minus odd is always odd: 10 \u2212 3 = 7.' },
  { emoji: '\uD83D\uDCA5', text: 'Multiplying two odd numbers gives an odd number: 3 \u00D7 5 = 15.' },
  { emoji: '\uD83D\uDCA5', text: 'If you multiply any number by an even number, the answer is always even.' },
  { emoji: '\uD83D\uDD1F', text: 'The 10 times table always ends in 0: 10, 20, 30, 40...' },
  { emoji: '\uD83D\uDD22', text: 'The 11 times table has a pattern up to 9: 11, 22, 33, 44... same digit twice!' },
  { emoji: '\uD83E\uDDE0', text: 'A shortcut for x4 is to double twice: 4 \u00D7 7 = double 7 (14), double again (28).' },
  { emoji: '\u26A1', text: 'A shortcut for x8 is to double three times: 8 \u00D7 3 = 3, 6, 12, 24.' },
  { emoji: '\uD83D\uDCDD', text: 'The plus sign (+) and minus sign (\u2212) first appeared in a book over 500 years ago.' },
  { emoji: '\u2716\uFE0F', text: 'The multiplication cross (\u00D7) was first used by William Oughtred in 1631.' },
  { emoji: '\u2797', text: 'The division sign (\u00F7) is called an obelus. The dots stand for numbers!' },
  { emoji: '\uD83D\uDD22', text: 'Roman numerals use letters: I=1, V=5, X=10, L=50, C=100.' },
  { emoji: '\uD83C\uDFDB\uFE0F', text: 'The Romans had no symbol for zero - the idea of zero came from India.' },
  { emoji: '\uD83E\uDDEE', text: 'The word "calculate" comes from "calculus", the Latin word for a little stone used to count.' },
  { emoji: '\uD83D\uDD22', text: 'A "score" means 20. So three score is 60.' },
  { emoji: '\uD83E\uDD5A', text: 'Eggs are sold in a dozen (12) because 12 shares evenly by 2, 3, 4 and 6.' },
  { emoji: '\uD83D\uDD52', text: 'Time uses 60s because 60 divides neatly by lots of numbers: 2, 3, 4, 5, 6...' },
  { emoji: '\uD83D\uDCCF', text: 'A ruler usually shows centimetres, and there are 100 of them in a metre.' },
  { emoji: '\uD83D\uDCCF', text: 'There are 1,000 metres in a kilometre.' },
  { emoji: '\u2696\uFE0F', text: 'There are 1,000 grams in a kilogram.' },
  { emoji: '\uD83E\uDD64', text: 'There are 1,000 millilitres in a litre.' },
  { emoji: '\uD83D\uDD22', text: 'Any number that ends in 5 or 0 can be divided exactly by 5.' },
  { emoji: '\uD83D\uDD22', text: 'If a number is even and divides by 3, it also divides by 6.' },
  { emoji: '\u2728', text: 'To check if a number divides by 3, add its digits: 51 -> 5 + 1 = 6, and 6 \u00F7 3 works.' },
  { emoji: '\uD83D\uDD0D', text: 'To check if a number divides by 9, add its digits and see if the total divides by 9.' },
  { emoji: '\uD83C\uDF1F', text: 'Zero is an even number, because it sits between two odd numbers, 1 and -1.' },
  { emoji: '\uD83E\uDDEE', text: 'The smallest two-digit number is 10, and the biggest is 99.' },
  { emoji: '\uD83D\uDD22', text: 'The smallest three-digit number is 100, and the biggest is 999.' },
  { emoji: '\uD83E\uDD1D', text: 'Two numbers that add up to 10 are called number bonds: 7 and 3, 6 and 4, 8 and 2.' },
  { emoji: '\uD83E\uDDE0', text: 'Learning number bonds to 10 makes adding bigger numbers much faster.' },
  { emoji: '\uD83D\uDD03', text: 'To subtract 9, subtract 10 and add 1 back: 25 \u2212 9 = 25 \u2212 10 + 1 = 16.' },
  { emoji: '\u26A1', text: 'To add 9, add 10 and take 1 away: 34 + 9 = 34 + 10 \u2212 1 = 43.' },
  { emoji: '\uD83C\uDFB0', text: 'The number 7 is many people\u2019s favourite - and it is a prime number too.' },
  { emoji: '\uD83C\uDF00', text: 'A circle has no corners and no straight sides at all.' },
  { emoji: '\uD83E\uDDCA', text: 'A cube has 6 square faces, 12 edges and 8 corners.' },
  { emoji: '\uD83C\uDFB2', text: 'A dice is a cube, so all its faces are squares.' },
  { emoji: '\uD83D\uDCE6', text: 'Volume tells you how much space fills a box: length \u00D7 width \u00D7 height.' },
  { emoji: '\uD83D\uDCD0', text: 'Area is the space inside a flat shape: a 3 by 4 rectangle has an area of 12.' },
  { emoji: '\uD83D\uDCCF', text: 'Perimeter is the distance all the way around the edge of a shape.' },
  { emoji: '\uD83D\uDD22', text: 'Counting numbers (1, 2, 3, 4...) go on forever - they never run out.' },
  { emoji: '\uD83E\uDD2F', text: 'A "googol" is a 1 followed by one hundred zeros - a truly enormous number!' },
  { emoji: '\uD83E\uDDD1\u200D\uD83C\uDFEB', text: 'The special number pi (\u03C0) is about 3.14 and helps measure circles.' },
  { emoji: '\uD83C\uDF70', text: 'People eat pie on Pi Day - the 14th of March, written 3.14!' },
  { emoji: '\uD83D\uDD01', text: 'Any number multiplied by itself an even number of times stays positive.' },
  { emoji: '\uD83E\uDDEE', text: 'Estimating means making a smart guess - handy when you do not need the exact answer.' },
  { emoji: '\uD83D\uDCCA', text: 'Rounding 47 to the nearest ten gives 50, because 47 is closer to 50 than to 40.' },
  { emoji: '\uD83D\uDD22', text: 'The digit\u2019s place matters: in 253 the 5 means fifty, not five.' },
  { emoji: '\uD83C\uDF89', text: 'Practising a little every day is the best trick for getting fast at maths!' },
];

// Return one random fun fact.
export function randomFact() {
  return FACTS[Math.floor(Math.random() * FACTS.length)];
}

// Return a random fact that is different from `prev` (best-effort).
export function anotherFact(prevText) {
  if (FACTS.length <= 1) return FACTS[0];
  let f = randomFact();
  let guard = 0;
  while (f.text === prevText && guard++ < 8) f = randomFact();
  return f;
}

export function factCount() { return FACTS.length; }
